/**
 * Shared medieval theme constants and components used across the Valkenhall UI.
 * Single source of truth for the dark-gold medieval aesthetic.
 */
import { playUI, UI } from '../utils/arena/uiSounds';

/* ── Color tokens ──────────────────────────────────────── */
export const GOLD = 'rgba(180, 140, 60,';
export const GOLD_TEXT = 'rgba(201, 168, 76,';
export const PARCHMENT = 'rgba(228, 213, 160,';
export const PANEL_BG = 'rgba(12, 10, 8, 0.92)';
export const PANEL_BORDER = `${GOLD} 0.25)`;
export const TEXT_PRIMARY = '#e8d5a0';
export const TEXT_BODY = '#A6A09B';
export const TEXT_MUTED = 'rgba(166, 160, 155, 0.5)';
export const COIN_COLOR = '#f0d060';
export const ACCENT_GOLD = '#d4a843';
export const DARK_BASE = '#08080a';

/* ── Atmospheric background ────────────────────────────── */
export const BG_ATMOSPHERE = [
  'radial-gradient(ellipse 80% 50% at 50% 30%, rgba(180,140,60,0.05) 0%, transparent 70%)',
  'radial-gradient(ellipse 60% 40% at 50% 80%, rgba(120,80,30,0.06) 0%, transparent 60%)',
  'radial-gradient(ellipse 100% 100% at 50% 50%, rgba(30,20,8,0.4) 0%, transparent 80%)',
  'radial-gradient(circle at 20% 20%, rgba(100,60,20,0.03) 0%, transparent 40%)',
  'radial-gradient(circle at 80% 70%, rgba(100,60,20,0.03) 0%, transparent 40%)',
  DARK_BASE,
].join(', ');

export const VIGNETTE = 'radial-gradient(ellipse 70% 60% at 50% 50%, transparent 40%, rgba(0,0,0,0.5) 100%)';

/* ── Noise texture for medieval grit ──────────────────── */
const NOISE_SVG = 'url("/tex-noise.webp")';
const NOISE_GOLD_SVG = 'url("/tex-noise-gold.webp")';
/* ── Pre-baked textures (static WebP files, generated by scripts/bake-textures.js) ── */
const STONE_TEX = 'url("/tex-stone.webp")';
const CHISEL_TEX = 'url("/tex-chisel.webp")';
const SCRATCHES_TEX = 'url("/tex-scratches.webp")';
const CRACKS_TEX = 'url("/tex-cracks.webp")';


/* ── Beveled button base ───────────────────────────────── */
export const BEVELED_BTN = {
  background: `${STONE_TEX}, ${CHISEL_TEX}, ${SCRATCHES_TEX}, ${CRACKS_TEX}, ${NOISE_SVG}, linear-gradient(180deg, rgba(255,255,255,0.07) 0%, rgba(0,0,0,0.12) 100%)`,
  border: `1px solid ${GOLD} 0.3)`,
  boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.06), inset 0 -1px 0 rgba(0,0,0,0.15), inset 0 0 8px rgba(0,0,0,0.12), 0 2px 8px rgba(0,0,0,0.4)',
  borderRadius: '8px',
  textShadow: '0 1px 2px rgba(0,0,0,0.5)',
};

/* ── Content background gradients ──────────────────────── */
export const CONTENT_BG_DEFAULT = `${STONE_TEX}, ${CHISEL_TEX}, ${SCRATCHES_TEX}, ${CRACKS_TEX}, ${NOISE_SVG}, linear-gradient(180deg, rgba(255,255,255,0.04) 0%, rgba(0,0,0,0.08) 100%)`;
export const CONTENT_BG_HOVER = `${STONE_TEX}, ${CHISEL_TEX}, ${SCRATCHES_TEX}, ${CRACKS_TEX}, ${NOISE_SVG}, linear-gradient(180deg, rgba(255,255,255,0.08) 0%, rgba(0,0,0,0.04) 100%)`;
export const CONTENT_BG_ACTIVE = `${STONE_TEX}, ${CHISEL_TEX}, ${SCRATCHES_TEX}, ${CRACKS_TEX}, ${NOISE_SVG}, linear-gradient(180deg, rgba(0,0,0,0.06) 0%, rgba(255,255,255,0.02) 100%)`;

/* ── Corner plating tokens ─────────────────────────────── */
export const CORNER_SIZE = 14;
export const CORNER_THICKNESS = 2;
export const BTN_BORDER = 'rgba(166,160,155,0.3)';
export const BTN_BORDER_HOVER = 'rgba(166,160,155,0.55)';
export const BTN_CORNER = 'rgba(166,160,155,0.5)';
export const BTN_CORNER_HOVER = 'rgba(166,160,155,0.85)';
export const GOLD_CORNER = `${GOLD} 0.45)`;

/* ── Panel / Dialog styles ─────────────────────────────── */
export const DIALOG_BG = 'linear-gradient(180deg, rgba(25,20,10,0.98) 0%, rgba(15,12,6,0.98) 100%)';
export const DIALOG_BORDER = `${GOLD} 0.3)`;
export const DIALOG_SHADOW = '0 0 60px rgba(0,0,0,0.5), 0 0 30px rgba(180,140,60,0.05)';

export const PANEL_STYLE = {
  background: PANEL_BG,
  border: `1px solid ${PANEL_BORDER}`,
  borderRadius: '8px',
};

export const DIALOG_STYLE = {
  background: DIALOG_BG,
  border: `1px solid ${DIALOG_BORDER}`,
  borderRadius: '12px',
  boxShadow: DIALOG_SHADOW,
  // isolation: isolate creates a new stacking context for the dialog
  // panel. This is what lets the embossed Borre knots in FourCorners
  // sit at z-index: -1 (behind static content) without escaping past
  // the panel into the page-level stacking context.
  isolation: 'isolate',
};

/* ── Gold primary button ───────────────────────────────── */
export const GOLD_BTN = {
  background: `${STONE_TEX}, ${CHISEL_TEX}, ${SCRATCHES_TEX}, ${CRACKS_TEX}, ${NOISE_GOLD_SVG}, linear-gradient(180deg, rgba(212,168,67,0.9) 0%, rgba(180,140,50,0.85) 50%, rgba(160,120,40,0.9) 100%)`,
  border: '1px solid rgba(228,200,100,0.6)',
  borderRadius: '6px',
  color: '#1a1408',
  boxShadow: '0 0 20px rgba(212,168,67,0.2), inset 0 1px 0 rgba(255,255,255,0.15), inset 0 -1px 0 rgba(0,0,0,0.2), inset 0 0 6px rgba(120,80,20,0.15)',
  textShadow: '0 1px 0 rgba(255,255,255,0.15)',
};

/* ── Danger / destructive button ───────────────────────── */
export const DANGER_BTN = {
  background: `${STONE_TEX}, ${CHISEL_TEX}, ${SCRATCHES_TEX}, ${CRACKS_TEX}, ${NOISE_SVG}, linear-gradient(180deg, rgba(180,60,60,0.15) 0%, rgba(120,30,30,0.1) 100%)`,
  border: `1px solid rgba(180,60,60,0.35)`,
  borderRadius: '6px',
  color: '#c45050',
  boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.04), inset 0 -1px 0 rgba(0,0,0,0.12), inset 0 0 6px rgba(0,0,0,0.1)',
  textShadow: '0 1px 2px rgba(0,0,0,0.5)',
};

/* ── Input field ───────────────────────────────────────── */
export const INPUT_STYLE = {
  background: 'rgba(0,0,0,0.25)',
  border: `1px solid ${GOLD} 0.12)`,
  borderRadius: '4px',
  color: TEXT_BODY,
  boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.3)',
};

/* ── Tab styling helpers ───────────────────────────────── */
export const TAB_ACTIVE = {
  color: TEXT_PRIMARY,
  background: `${STONE_TEX}, ${CHISEL_TEX}, ${SCRATCHES_TEX}, ${NOISE_SVG}, ${GOLD} 0.12)`,
  border: `1px solid ${GOLD} 0.3)`,
  borderRadius: '4px',
  boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.04), inset 0 -1px 0 rgba(0,0,0,0.1)',
  textShadow: '0 1px 2px rgba(0,0,0,0.5)',
};

export const TAB_INACTIVE = {
  color: TEXT_MUTED,
  background: `${STONE_TEX}, ${NOISE_SVG}, transparent`,
  border: '1px solid rgba(166,160,155,0.1)',
  borderRadius: '4px',
};

/* ── Divider gradient ──────────────────────────────────── */
export const DIVIDER_GRADIENT = `linear-gradient(90deg, transparent 0%, ${GOLD} 0.25) 50%, transparent 100%)`;

/* ── Popover / context menu (in-game) ──────────────────── */
export const POPOVER_STYLE = {
  background: PANEL_BG,
  border: `1px solid ${GOLD} 0.2)`,
  borderRadius: '8px',
  boxShadow: '0 24px 80px rgba(0,0,0,0.4), 0 0 30px rgba(180,140,60,0.04)',
  // Same stacking-context isolation as DIALOG_STYLE so any embossed
  // ornaments (knots, centerpieces) inside a popover stay clipped to
  // the popover instead of escaping to the page level.
  isolation: 'isolate',
};

/* ── Scrollbar accent (css class) ──────────────────────── */
export const SECTION_HEADER_STYLE = {
  color: `${GOLD} 0.55)`,
  textShadow: `0 0 12px ${GOLD} 0.15)`,
};

/* ── Viewport scale factor (for large-screen scaling) ──── */
const HUB_DESIGN_WIDTH = 1600;

export function getViewportScale() {
  const vw = typeof window !== 'undefined' ? window.innerWidth : HUB_DESIGN_WIDTH;
  return Math.max(1, vw / HUB_DESIGN_WIDTH);
}

/* ── Shared debounced viewport scale listener ─────────── */
const scaleListeners = new Set();
let scaleRafId = null;

function handleScaleResize() {
  if (scaleRafId) return;
  scaleRafId = requestAnimationFrame(() => {
    scaleRafId = null;
    const scale = getViewportScale();
    document.documentElement.style.setProperty('--viewport-scale', scale);
    for (const fn of scaleListeners) fn(scale);
  });
}

if (typeof window !== 'undefined') {
  document.documentElement.style.setProperty('--viewport-scale', String(getViewportScale()));
  window.addEventListener('resize', handleScaleResize);
}

export function onViewportScaleChange(callback) {
  scaleListeners.add(callback);
  return () => scaleListeners.delete(callback);
}

/* ── Helper: alpha-adjust an rgba( prefix string ───────── */
export function adjustAlpha(rgba, alpha) {
  return rgba.replace(/[\d.]+\)$/, `${alpha})`);
}

/* ── Corner plating ornament ───────────────────────────── */
export function CornerPlating({ position, color = GOLD_CORNER, radius = 8 }) {
  const s = CORNER_SIZE;
  const t = CORNER_THICKNESS;
  const r = radius;
  const base = { zIndex: 2, width: s, height: s, transition: 'border-color 0.2s ease' };
  const styles = {
    'top-left': { ...base, top: -2, left: -2, borderTop: `${t}px solid ${color}`, borderLeft: `${t}px solid ${color}`, borderTopLeftRadius: r },
    'top-right': { ...base, top: -2, right: -2, borderTop: `${t}px solid ${color}`, borderRight: `${t}px solid ${color}`, borderTopRightRadius: r },
    'bottom-left': { ...base, bottom: -2, left: -2, borderBottom: `${t}px solid ${color}`, borderLeft: `${t}px solid ${color}`, borderBottomLeftRadius: r },
    'bottom-right': { ...base, bottom: -2, right: -2, borderBottom: `${t}px solid ${color}`, borderRight: `${t}px solid ${color}`, borderBottomRightRadius: r },
  };
  return <div className="absolute pointer-events-none" style={styles[position]} data-corner="" />;
}

/* ── Borre knot corner ─────────────────────────────────── */
//
// Small Viking knot tucked into one corner of a panel. Uses CSS
// mask-image so the wrapper div's background-color is what's actually
// rendered — meaning we can re-tint via the `color` prop without
// shipping multiple SVG variants.
//
// The knot is meant to feel ENGRAVED into the panel, sitting below
// every other content layer:
//
//   1. zIndex: -1 puts it at the bottom of the parent's stacking
//      context. The parent (DIALOG_STYLE / POPOVER_STYLE) sets
//      isolation: isolate so the knot stays clipped to the panel
//      instead of escaping to the page-level stacking context.
//
//   2. The neutral warm-white tint at low opacity blends with the
//      panel texture. The two-stop drop-shadow filter adds a 1px
//      warm highlight (offset down) and a 1px dark recess (offset up),
//      creating the relief that sells the embossed look.
//
//   3. mix-blend-mode: overlay further integrates the knot with
//      whatever's behind it: the strokes lift bright pixels and
//      darken shadows, the way an actual carving would catch light
//      across the panel's stone texture.
//
// The knot's natural orientation has a small upward triangle on top
// and a larger downward V on the bottom. We rotate each corner so the
// V faces INWARD toward the panel center, which feels like the knot
// is "closing" the corner.

// Per-session cache-bust — see VikingOrnament.jsx for the rationale.
// CEF treats CSS mask-image url() as long-lived cached resources, so a
// stable query string per app launch is the most reliable way to make
// edits to the SVG show up after a reload.
const KNOT_URL = `/game-assets/ornaments/viking-borre-knot.svg?v=${typeof Date !== 'undefined' ? Date.now() : 0}`;

const KNOT_ROTATIONS = {
  'top-left': 135,
  'top-right': -135,
  'bottom-left': 45,
  'bottom-right': -45,
};

export function KnotCorner({
  position,
  size = 40,
  inset = 6,
  color = 'rgba(232, 200, 130, 1)',
  opacity = 0.42,
}) {
  const [vertical, horizontal] = position.split('-');
  return (
    <div
      className="absolute pointer-events-none"
      style={{
        [vertical]: inset,
        [horizontal]: inset,
        width: size,
        height: size,
        transform: `rotate(${KNOT_ROTATIONS[position]}deg)`,
        maskImage: `url("${KNOT_URL}")`,
        WebkitMaskImage: `url("${KNOT_URL}")`,
        maskRepeat: 'no-repeat',
        WebkitMaskRepeat: 'no-repeat',
        maskPosition: 'center',
        WebkitMaskPosition: 'center',
        maskSize: 'contain',
        WebkitMaskSize: 'contain',
        backgroundColor: color,
        opacity,
        filter: 'drop-shadow(0 1px 0 rgba(255, 235, 195, 0.35)) drop-shadow(0 -1px 0 rgba(0, 0, 0, 0.85))',
        mixBlendMode: 'overlay',
        zIndex: -1,
      }}
      data-knot=""
    />
  );
}

/* ── Four knots shorthand ──────────────────────────────── */
//
// Drop-in companion to FourCorners. Use directly when you want only
// the knots, or pass `knots` to FourCorners to render both.
export function FourKnots({ size = 40, inset = 6, color, opacity }) {
  return (
    <>
      <KnotCorner position="top-left"     size={size} inset={inset} color={color} opacity={opacity} />
      <KnotCorner position="top-right"    size={size} inset={inset} color={color} opacity={opacity} />
      <KnotCorner position="bottom-left"  size={size} inset={inset} color={color} opacity={opacity} />
      <KnotCorner position="bottom-right" size={size} inset={inset} color={color} opacity={opacity} />
    </>
  );
}

/* ── Four corners shorthand ────────────────────────────── */
//
// Pass `knots` to also render the Borre knots in each corner. Use it
// for modal-style panels with enough space (typically 320px+ in both
// dimensions). Skip it on tiny things like toasts or loading spinners.
export function FourCorners({
  color = GOLD_CORNER,
  radius = 8,
  knots = false,
  knotSize = 40,
  knotInset = 6,
  knotColor,
  knotOpacity,
}) {
  return (
    <>
      <CornerPlating position="top-left" color={color} radius={radius} />
      <CornerPlating position="top-right" color={color} radius={radius} />
      <CornerPlating position="bottom-left" color={color} radius={radius} />
      <CornerPlating position="bottom-right" color={color} radius={radius} />
      {knots ? (
        <FourKnots size={knotSize} inset={knotInset} color={knotColor} opacity={knotOpacity} />
      ) : null}
    </>
  );
}

/* ── Ornamental divider with celtic rune ───────────────── */
export function OrnamentalDivider({ className }) {
  return (
    <div className={`flex items-center gap-3 select-none ${className || ''}`}>
      <div className="flex-1 h-px" style={{ background: DIVIDER_GRADIENT }} />
      <img src="/rune-divider.webp" alt="" className="h-5" draggable={false} style={{ opacity: 0.25, filter: 'sepia(1) saturate(3) brightness(0.6) hue-rotate(15deg)' }} />
      <div className="flex-1 h-px" style={{ background: DIVIDER_GRADIENT }} />
    </div>
  );
}

/* ── Medieval button component ────────────────────────── */
const VARIANT_SOUND = {
  default: UI.CLICK,
  confirm: UI.CONFIRM,
  cancel: UI.CANCEL,
  danger: UI.CANCEL,
  gold: UI.CONFIRM,
};

const VARIANT_STYLE = {
  default: 'BEVELED_BTN',
  confirm: 'GOLD_BTN',
  cancel: 'BEVELED_BTN',
  danger: 'DANGER_BTN',
  gold: 'GOLD_BTN',
};

export function MedievalBtn({ variant = 'default', sound, onClick, className = '', style: extraStyle, children, ...props }) {
  const baseStyle = variant === 'gold' || variant === 'confirm' ? GOLD_BTN
    : variant === 'danger' ? DANGER_BTN
    : BEVELED_BTN;
  const soundFile = sound === 'none' ? null : (sound || VARIANT_SOUND[variant] || UI.CLICK);

  return (
    <button
      type="button"
      className={`transition-all duration-200 hover:scale-[1.03] active:scale-[0.98] ${className}`}
      style={{ ...baseStyle, ...extraStyle }}
      onClick={(e) => {
        if (soundFile) playUI(soundFile);
        onClick?.(e);
      }}
      {...props}
    >
      {children}
    </button>
  );
}

/* ── Ornate menu button (used in hub, game menu, etc.) ── */
export function MenuButton({ title, onClick, style: extraStyle, dataTutorial }) {
  return (
    <button
      type="button"
      data-tutorial={dataTutorial}
      className="relative group w-full text-center cursor-pointer transition-all duration-200 mb-2"
      style={{ transform: 'scale(1)', ...extraStyle }}
      onMouseEnter={(e) => {
        const el = e.currentTarget;
        el.style.transform = 'scale(1.02)';
        el.style.boxShadow = '0 0 20px rgba(166,160,155,0.08)';
        el.querySelector('[data-frame]').style.borderColor = BTN_BORDER_HOVER;
        el.querySelectorAll('[data-corner]').forEach((c) => { c.style.borderColor = BTN_CORNER_HOVER; });
        el.querySelector('[data-content]').style.background = `${CONTENT_BG_HOVER}, rgba(12, 10, 8, 0.92)`;
      }}
      onMouseLeave={(e) => {
        const el = e.currentTarget;
        el.style.transform = 'scale(1)';
        el.style.boxShadow = 'none';
        el.querySelector('[data-frame]').style.borderColor = BTN_BORDER;
        el.querySelectorAll('[data-corner]').forEach((c) => { c.style.borderColor = BTN_CORNER; });
        el.querySelector('[data-content]').style.background = `${CONTENT_BG_DEFAULT}, rgba(12, 10, 8, 0.92)`;
      }}
      onMouseDown={(e) => {
        e.currentTarget.style.transform = 'scale(0.98)';
        e.currentTarget.querySelector('[data-content]').style.background = `${CONTENT_BG_ACTIVE}, rgba(12, 10, 8, 0.92)`;
      }}
      onMouseUp={(e) => {
        e.currentTarget.style.transform = 'scale(1.02)';
        e.currentTarget.querySelector('[data-content]').style.background = `${CONTENT_BG_HOVER}, rgba(12, 10, 8, 0.92)`;
      }}
      onClick={(e) => { playUI(UI.CLICK); onClick?.(e); }}
    >
      <div data-frame="" className="absolute inset-0 pointer-events-none" style={{ border: `1px solid ${BTN_BORDER}`, borderRadius: '6px', transition: 'border-color 0.2s ease' }} />
      <CornerPlating position="top-left" color={BTN_CORNER} />
      <CornerPlating position="top-right" color={BTN_CORNER} />
      <CornerPlating position="bottom-left" color={BTN_CORNER} />
      <CornerPlating position="bottom-right" color={BTN_CORNER} />

      <div data-content="" className="relative px-5 py-3.5 flex items-center justify-center" style={{ background: `${CONTENT_BG_DEFAULT}, rgba(12, 10, 8, 0.92)`, backdropFilter: 'blur(8px)', boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.05), inset 0 -1px 0 rgba(0,0,0,0.12), inset 0 0 8px rgba(0,0,0,0.1)', textShadow: '0 2px 4px rgba(0,0,0,0.8), 0 0 12px rgba(0,0,0,0.5)', borderRadius: '6px', transition: 'background 0.2s ease' }}>
        <span className="text-lg font-bold arena-heading" style={{ color: TEXT_PRIMARY }}>{title}</span>
      </div>
    </button>
  );
}
