export const FAB_SET_NAME_BY_ID = {
  '1HB': 'History Pack 1 - Bravo Blitz Deck',
  '1HD': 'History Pack 1 - Dash Blitz Deck',
  '1HK': 'History Pack 1 - Kano Blitz Deck',
  '1HP': 'History Pack 1',
  '1HR': 'History Pack 1 - Rhinar Blitz Deck',
  '1HT': 'History Pack 1 - Dorinthea Blitz Deck',
  '1HV': 'History Pack 1 - Viserai Blitz Deck',
  AAC: 'Armory Deck - Arakni',
  AAZ: 'Armory Deck - Azalea',
  AGB: 'Armory Deck - Gravy Bones',
  AIO: 'Armory Deck - Dash I/O',
  AJV: 'Armory Deck Origins - Jarl Vetreiði',
  AKO: 'Armory Deck - Kayo',
  AMX: 'Amory Deck - Maxx',
  APR: 'Armory Deck Legends - Prism',
  APS: 'Armory Deck - Pleiades',
  ARA: 'Arakni Blitz Deck',
  ARC: 'Arcane Rising',
  ARK: 'Arakni Blitz Deck',
  ARR: 'Armory Deck - Rhinar',
  ASB: 'Armory Deck - Boltyn',
  ASR: 'Armory Deck - Ira',
  AST: 'Armory Deck - Aurora',
  AUA: 'Aurora Blitz Deck',
  AUR: 'First Strike - Aurora',
  AVS: 'Armory Deck Legends - Viserai',
  AZL: 'Azalea Blitz Deck',
  BDD: 'Bravo Demo Deck',
  BEN: 'Benji Blitz Deck',
  BET: 'Betsy Blitz Deck',
  BOL: 'Boltyn Blitz Deck',
  BRI: 'Briar Blitz Deck',
  BVO: 'Bravo Hero Deck',
  CHN: 'Chane Blitz Deck',
  CIN: 'Cindra Blitz Deck',
  CRU: 'Crucible of War',
  DRO: 'Dromai Blitz Deck',
  DTD: 'Dusk till Dawn',
  DVR: 'Classic Battles: Rhinar vs Dorinthea - Dorinthea',
  DYN: 'Dynasty',
  ELE: 'Tales of Aria',
  ENG: 'Enigma Blitz Deck',
  EVO: 'Bright Lights',
  EVR: 'Everfest',
  FAB: 'Promos',
  FAI: 'Fai Blitz Deck',
  FLR: 'Florian Blitz Deck',
  FNG: 'Fang Blitz Deck',
  GEM: 'GEM Pack Promos',
  HER: 'Hero Card Promos',
  HNT: 'The Hunted',
  HVY: 'Heavy Hitters',
  IRA: 'Ira Welcome Deck',
  JDG: 'Judge Unique Promos',
  KAT: 'Katsu Blitz Deck',
  KSI: 'Kassai Blitz Deck',
  KSU: 'Katsu Hero Deck',
  KYO: 'Kayo Blitz Deck',
  LEV: 'Levia Blitz Deck',
  LGS: 'Local Game Store Promos',
  LSS: 'LSS Promos',
  LXI: 'Lexi Blitz Deck',
  MON: 'Monarch',
  MPG: 'Mastery Pack Guardian',
  MST: 'Part the Mistveil',
  NUU: 'Nuu Blitz Deck',
  OLA: 'Olympia Blitz Deck',
  OLD: 'Oldhim Blitz Deck',
  OSC: 'Oscilio Blitz Deck',
  OUT: 'Outsiders',
  OXO: 'Slingshot Underground Promos',
  PSM: 'Prism Blitz Deck',
  RHI: 'Rhinar Blitz Deck',
  RIP: 'Riptide Blitz Deck',
  RNR: 'Rhinar Hero Deck',
  ROS: 'Rosetta',
  RVD: 'Classic Battles: Rhinar vs Dorinthea - Rhinar',
  SEA: 'High Seas',
  SMP: 'Smash Palace',
  SUP: 'Super Slam',
  TCC: 'Round the Table: TCC X LSS',
  TEA: 'Dorinthea Hero Deck',
  TER: 'First Strike - Terra',
  UPR: 'Uprising',
  UZU: 'Uzuri Blitz Deck',
  VER: 'Verdance Blitz Deck',
  VIC: 'Victor Goldmane Blitz Deck',
  WIN: 'Worlds / Pro Tour Prize Cards',
  WOD: 'Arakni, Web of Deceit Blitz Deck',
  WTR: 'Welcome to Rathe',
  XXX: 'OP Event Tokens',
  ZEN: 'Zen Blitz Deck',
};
