import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  renameSync,
  statSync,
  chmodSync,
} from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';

const APP_ID = 'dev.fabianurbanek.valkenhall';
const APP_NAME = 'Valkenhall';
const DESKTOP_ENTRY_SPEC_VERSION = '1.5';

// Uninstall script template. Placeholders __ID__ and __CHANNEL__ are
// replaced at write time. All other variables resolve at script run time
// from the user's environment ($HOME, $XDG_DATA_HOME, $XDG_CACHE_HOME).
// Keeping the template as a JS string means the module is the single
// source of truth for everything a launch-time bootstrap writes to disk.
const UNINSTALL_SCRIPT_TEMPLATE = `#!/usr/bin/env bash
#
# Valkenhall uninstaller. Generated by the app on first launch.
# You can also run this script directly from a terminal.
#
set -eu

ID="__ID__"
CHANNEL="__CHANNEL__"
APP_NAME="Valkenhall"

DATA_HOME="\${XDG_DATA_HOME:-$HOME/.local/share}"
CACHE_HOME="\${XDG_CACHE_HOME:-$HOME/.cache}"
INSTALL_DIR="$DATA_HOME/$ID/$CHANNEL"
USER_DATA_DIR="$DATA_HOME/$ID/data"
CACHE_ROOT="$CACHE_HOME/$ID"
CHANNEL_CACHE_DIR="$CACHE_ROOT/$CHANNEL"
APPS_DIR="$DATA_HOME/applications"
DESKTOP_DIR="$(xdg-user-dir DESKTOP 2>/dev/null || echo "$HOME/Desktop")"

display_name="$APP_NAME"
if [ "$CHANNEL" != "stable" ]; then
  display_name="$APP_NAME ($CHANNEL)"
fi

cat <<INFO
Uninstall $display_name?

This will remove:
  $INSTALL_DIR
  $CHANNEL_CACHE_DIR
  $APPS_DIR/$ID.$CHANNEL.desktop
  $APPS_DIR/$ID.$CHANNEL.uninstall.desktop
  $DESKTOP_DIR/$APP_NAME.desktop (if present)

Your user data (preferences, auth token, downloaded card images) will be
kept unless you say otherwise at the next prompt.

INFO
printf "Continue? [y/N] "
read -r reply
case "$reply" in
  y|Y|yes|YES) ;;
  *) echo "Aborted."; exit 1 ;;
esac

rm -rf "$CHANNEL_CACHE_DIR"
# If the cache root has no other channels left, drop it.
rmdir "$CACHE_ROOT" 2>/dev/null || true

rm -f "$APPS_DIR/$ID.$CHANNEL.desktop"
rm -f "$APPS_DIR/$ID.$CHANNEL.uninstall.desktop"
rm -f "$DESKTOP_DIR/$APP_NAME.desktop"

update-desktop-database "$APPS_DIR" 2>/dev/null || true

if [ -d "$USER_DATA_DIR" ]; then
  echo
  echo "User data lives at: $USER_DATA_DIR"
  printf "Also remove user data? [y/N] "
  read -r reply
  case "$reply" in
    y|Y|yes|YES)
      rm -rf "$USER_DATA_DIR"
      echo "User data removed."
      ;;
    *)
      echo "User data kept."
      ;;
  esac
fi

# Remove the install dir last — this file is inside it and will delete
# itself. Bash has already loaded the script into memory, so the
# in-flight execution survives the unlink.
rm -rf "$INSTALL_DIR"
# If the identifier dir is now empty (no other channels, no user data),
# remove the empty husk so nothing stale is left behind.
rmdir "$DATA_HOME/$ID" 2>/dev/null || true

echo
echo "$display_name uninstalled."
printf "Press Enter to close..."
read -r _ || true
`;

export function renderUninstallScript(channel) {
  return UNINSTALL_SCRIPT_TEMPLATE
    .replaceAll('__ID__', APP_ID)
    .replaceAll('__CHANNEL__', channel);
}

export function ensureLinuxDesktopEntry(overrides = {}) {
  if ((overrides.platform || process.platform) !== 'linux') {
    return false;
  }
  try {
    const layout = resolveBundleLayout(overrides);
    if (!layout) return false;

    const targetDir = resolveApplicationsDir(overrides);
    if (!targetDir) return false;

    const channelDir = path.dirname(layout.bundleRoot);
    const scriptPath = ensureUninstallScript(channelDir, layout.channel);

    let wrote = false;
    if (writeMainEntry(targetDir, layout)) wrote = true;
    if (writeUninstallEntry(targetDir, layout, scriptPath)) wrote = true;

    if (wrote) refreshDesktopDatabase(targetDir);
    return wrote;
  } catch (err) {
    console.warn('[linuxDesktopEntry] failed:', err?.message || err);
    return false;
  }
}

function writeMainEntry(targetDir, layout) {
  const filename = `${APP_ID}.${layout.channel}.desktop`;
  const targetPath = path.join(targetDir, filename);
  if (!needsWrite(targetPath, layout.launcherPath)) return false;
  mkdirSync(targetDir, { recursive: true });
  atomicWrite(targetPath, buildDesktopEntry(layout));
  return true;
}

function writeUninstallEntry(targetDir, layout, scriptPath) {
  const filename = `${APP_ID}.${layout.channel}.uninstall.desktop`;
  const targetPath = path.join(targetDir, filename);
  if (!needsWrite(targetPath, scriptPath)) return false;
  mkdirSync(targetDir, { recursive: true });
  atomicWrite(targetPath, buildUninstallDesktopEntry({ ...layout, scriptPath }));
  return true;
}

export function ensureUninstallScript(channelDir, channel) {
  const scriptPath = path.join(channelDir, 'uninstall.sh');
  const contents = renderUninstallScript(channel);

  let current = null;
  try {
    current = readFileSync(scriptPath, 'utf8');
  } catch {
    // missing or unreadable — treat as needs-write
  }

  if (current !== contents) {
    mkdirSync(channelDir, { recursive: true });
    atomicWrite(scriptPath, contents);
  }
  try {
    chmodSync(scriptPath, 0o755);
  } catch {
    // read-only FS — non-fatal, the file is still usable via `bash script.sh`
  }
  return scriptPath;
}

export function buildUninstallDesktopEntry({ iconPath, channel, scriptPath }) {
  const isStable = channel === 'stable';
  const displayName = isStable
    ? `Uninstall ${APP_NAME}`
    : `Uninstall ${APP_NAME} (${channel})`;
  const execValue = quoteExecArgument(scriptPath);

  const lines = [
    '[Desktop Entry]',
    'Type=Application',
    `Version=${DESKTOP_ENTRY_SPEC_VERSION}`,
    `Name=${displayName}`,
    `GenericName=Uninstaller`,
    `Comment=Remove ${APP_NAME} from your system`,
    `Exec=${execValue}`,
    `TryExec=${scriptPath}`,
    `Icon=${iconPath}`,
    'Terminal=true',
    'Categories=System;',
    'StartupNotify=false',
    `X-Valkenhall-Channel=${channel}`,
    '',
  ];
  return lines.join('\n');
}

// Inside an installed Electrobun Linux bundle, `process.execPath` is the
// `bin/bun` runtime that was spawned by `bin/launcher`. The launcher sets
// up LD_PRELOAD (libcef.so + libvk_swiftshader.so) before exec'ing bun, so
// menu entries MUST point at the launcher — invoking `bin/bun` directly
// bypasses LD_PRELOAD and CEF fails to initialize. We derive the bundle
// root from execPath but always use `<bundleRoot>/bin/launcher` for Exec.
export function resolveBundleLayout(overrides = {}) {
  const execPath = overrides.execPath || process.execPath;
  if (!execPath || !path.isAbsolute(execPath)) return null;

  const bundleRoot = path.resolve(execPath, '..', '..');
  if (path.basename(bundleRoot) !== 'app') return null;

  const channelDir = path.resolve(bundleRoot, '..');
  const channel = path.basename(channelDir) || 'stable';
  const launcherPath = path.join(bundleRoot, 'bin', 'launcher');
  const iconPath = path.join(bundleRoot, 'Resources', 'appIcon.png');

  if (overrides.skipFsCheck !== true) {
    try {
      if (!statSync(launcherPath).isFile()) return null;
    } catch {
      return null;
    }
  }

  return { launcherPath, bundleRoot, iconPath, channel };
}

function resolveApplicationsDir(overrides = {}) {
  const env = overrides.env || process.env;
  const home = overrides.homedir ? overrides.homedir() : os.homedir();
  const xdgDataHome = env.XDG_DATA_HOME && env.XDG_DATA_HOME.trim();
  const base = xdgDataHome && path.isAbsolute(xdgDataHome)
    ? xdgDataHome
    : home
      ? path.join(home, '.local', 'share')
      : null;
  if (!base) return null;
  return path.join(base, 'applications');
}

export function buildDesktopEntry({ launcherPath, iconPath, channel }) {
  const isStable = channel === 'stable';
  const displayName = isStable ? APP_NAME : `${APP_NAME} (${channel})`;
  const execValue = `${quoteExecArgument(launcherPath)} %U`;

  const lines = [
    '[Desktop Entry]',
    'Type=Application',
    `Version=${DESKTOP_ENTRY_SPEC_VERSION}`,
    `Name=${displayName}`,
    'GenericName=Card Game Arena',
    'Comment=Desktop arena for Flesh and Blood and Sorcery TCG',
    `Exec=${execValue}`,
    `TryExec=${launcherPath}`,
    `Icon=${iconPath}`,
    'Terminal=false',
    'Categories=Game;CardGame;',
    'StartupNotify=true',
    `StartupWMClass=${APP_NAME}`,
    `X-Valkenhall-Channel=${channel}`,
    '',
  ];
  return lines.join('\n');
}

function quoteExecArgument(arg) {
  if (!/[\s"`$\\]/.test(arg)) return arg;
  const escaped = arg.replace(/(["`$\\])/g, '\\$1');
  return `"${escaped}"`;
}

function needsWrite(targetPath, expectedLauncherPath) {
  if (!existsSync(targetPath)) return true;
  let contents;
  try {
    contents = readFileSync(targetPath, 'utf8');
  } catch {
    return true;
  }
  const match = contents.match(/^Exec=(.*)$/m);
  if (!match) return true;

  const firstArg = parseFirstExecArg(match[1]);
  return firstArg !== expectedLauncherPath;
}

function parseFirstExecArg(value) {
  const trimmed = value.trimStart();
  if (trimmed.startsWith('"')) {
    let out = '';
    let i = 1;
    while (i < trimmed.length) {
      const ch = trimmed[i];
      if (ch === '\\' && i + 1 < trimmed.length) {
        out += trimmed[i + 1];
        i += 2;
        continue;
      }
      if (ch === '"') return out;
      out += ch;
      i += 1;
    }
    return out;
  }
  const space = trimmed.indexOf(' ');
  return space === -1 ? trimmed : trimmed.slice(0, space);
}

function atomicWrite(targetPath, contents) {
  const tmp = `${targetPath}.tmp`;
  writeFileSync(tmp, contents, { encoding: 'utf8', mode: 0o644 });
  renameSync(tmp, targetPath);
}

function refreshDesktopDatabase(applicationsDir) {
  try {
    spawnSync('update-desktop-database', [applicationsDir], {
      stdio: 'ignore',
      timeout: 2000,
    });
  } catch {
    // ignore — missing on minimal systems is fine; DEs typically watch the dir.
  }
}
